openapi: 3.2.0
info:
  title: YOOBIC Public Geofilters API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Geofilters
  description: 'provides a mapping between users and the stores they have permission to visit


    - Each user may have more than one store mapped.'
paths:
  /public/api/geofilters/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  geofilter_id:
                    type: string
                  store_ids:
                    type: array
                    items:
                      type: string
                  store_type_ids:
                    type: array
                    items:
                      type: string
                  user_id:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  geofilter_id: 552168f5f8d75fe77c520e7f
                  store_ids:
                  - 551d6add1077d5fb7a12cd33
                  - 551da1d6e846db5b384876e3
                  - 551d6addc5ba3e1c05027f75
                  - 551d6adddf86ce073a80903b
                  - 551d6add6356be82480274c0
                  - 551d6add2c35374276027fe9
                  - 54f06ac41e93dff83d000857
                  store_type_ids:
                  - 551c1b9b11cbd1e27819ea0f
                  - 551bc51e0a122f7f73e04ba7
                  - 551b1a44e829ce22380028f4
                  - 54357be802d0e9fa0202e9a2
                  user_id: 55142883b0cc8a622d01c5a1
                  created_date: '2015-04-05T16:55:17.563Z'
                  updated_date: '2015-09-07T09:10:58.643Z'
              examples:
                response:
                  value:
                    geofilter_id: 552168f5f8d75fe77c520e7f
                    store_ids:
                    - 551d6add1077d5fb7a12cd33
                    - 551da1d6e846db5b384876e3
                    - 551d6addc5ba3e1c05027f75
                    - 551d6adddf86ce073a80903b
                    - 551d6add6356be82480274c0
                    - 551d6add2c35374276027fe9
                    - 54f06ac41e93dff83d000857
                    store_type_ids:
                    - 551c1b9b11cbd1e27819ea0f
                    - 551bc51e0a122f7f73e04ba7
                    - 551b1a44e829ce22380028f4
                    - 54357be802d0e9fa0202e9a2
                    user_id: 55142883b0cc8a622d01c5a1
                    created_date: '2015-04-05T16:55:17.563Z'
                    updated_date: '2015-09-07T09:10:58.643Z'
      summary: Get
      operationId: Get
      description: Get a geofilter for the given id.
      tags:
      - Geofilters
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
    delete:
      responses:
        '204':
          description: No Content
          headers: {}
      summary: Delete
      operationId: Delete
      description: Delete a geofilter by id.
      tags:
      - Geofilters
      security:
      - oauth2: []
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  geofilter_id:
                    type: string
                  store_ids:
                    type: array
                    items:
                      type: string
                  store_type_ids:
                    type: array
                    items:
                      type: string
                  user_id:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  geofilter_id: 552168f5f8d75fe77c520e7f
                  store_ids:
                  - 551d6add1077d5fb7a12ab01
                  store_type_ids:
                  - 551c1b9b11cbd1e27819ea0f
                  - 551bc51e0a122f7f73e04ba7
                  - 551b1a44e829ce22380028f4
                  - 54357be802d0e9fa0202e9a2
                  user_id: 55142883b0cc8a622d01c5a1
                  created_date: '2015-04-05T01:55:17.563Z'
                  updated_date: '2015-09-07T11:30:58.643Z'
              examples:
                response:
                  value:
                    geofilter_id: 552168f5f8d75fe77c520e7f
                    store_ids:
                    - 551d6add1077d5fb7a12ab01
                    store_type_ids:
                    - 551c1b9b11cbd1e27819ea0f
                    - 551bc51e0a122f7f73e04ba7
                    - 551b1a44e829ce22380028f4
                    - 54357be802d0e9fa0202e9a2
                    user_id: 55142883b0cc8a622d01c5a1
                    created_date: '2015-04-05T01:55:17.563Z'
                    updated_date: '2015-09-07T11:30:58.643Z'
      summary: Partial Update
      operationId: Partial Update
      description: Update a subset of properties of a geofilter
      tags:
      - Geofilters
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                store_client_ids:
                  type: array
                  items:
                    type: string
              example:
                store_client_ids:
                - ice-cream-store-10
      security:
      - oauth2: []
  /public/api/geofilters?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        geofilter_id:
                          type: string
                        store_ids:
                          type: array
                          items:
                            type: string
                        store_type_ids:
                          type: array
                          items:
                            type: string
                        user_id:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - geofilter_id
                      - store_ids
                      - user_id
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - geofilter_id: 552168f5f8d75fe77c520e7f
                    store_ids:
                    - 551d6add1077d5fb7a12ab01
                    store_type_ids:
                    - 551c1b9b11cbd1e27819ea0f
                    - 551bc51e0a122f7f73e04ba7
                    - 551b1a44e829ce22380028f4
                    - 54357be802d0e9fa0202e9a2
                    user_id: 55142883b0cc8a622d01c5a1
                    created_date: '2015-04-05T01:55:17.563Z'
                    updated_date: '2015-09-07T11:30:58.643Z'
                  - geofilter_id: 552168f5f8d75fe77c520e80
                    store_ids:
                    - 551d6add1077d5fb7a12ab02
                    - 551d6add1077d5fb7a12ab03
                    user_id: 55142883b0cc8a622d01c5a2
                    created_date: '2015-04-05T01:55:17.563Z'
                    updated_date: '2015-09-07T11:40:58.643Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - geofilter_id: 552168f5f8d75fe77c520e7f
                      store_ids:
                      - 551d6add1077d5fb7a12ab01
                      store_type_ids:
                      - 551c1b9b11cbd1e27819ea0f
                      - 551bc51e0a122f7f73e04ba7
                      - 551b1a44e829ce22380028f4
                      - 54357be802d0e9fa0202e9a2
                      user_id: 55142883b0cc8a622d01c5a1
                      created_date: '2015-04-05T01:55:17.563Z'
                      updated_date: '2015-09-07T11:30:58.643Z'
                    - geofilter_id: 552168f5f8d75fe77c520e80
                      store_ids:
                      - 551d6add1077d5fb7a12ab02
                      - 551d6add1077d5fb7a12ab03
                      user_id: 55142883b0cc8a622d01c5a2
                      created_date: '2015-04-05T01:55:17.563Z'
                      updated_date: '2015-09-07T11:40:58.643Z'
      summary: Get all
      operationId: Get all
      description: Get all geofilters.
      tags:
      - Geofilters
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/geofilters/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Geofilters
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/geofilters:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    geofilter_id:
                      type: string
                    store_ids:
                      type: array
                      items:
                        type: string
                    user_id:
                      type: string
                    created_date:
                      type: string
                    updated_date:
                      type: string
                  required:
                  - geofilter_id
                  - store_ids
                  - user_id
                  - created_date
                  - updated_date
                example:
                - geofilter_id: 552168f5f8d75fe77c520e7f
                  store_ids:
                  - 551d6add1077d5fb7a12ab01
                  user_id: 55142883b0cc8a622d01c5a1
                  created_date: '2015-04-05T01:55:17.563Z'
                  updated_date: '2015-09-07T11:30:58.643Z'
                - geofilter_id: 552168f5f8d75fe77c520e80
                  store_ids:
                  - 551d6add1077d5fb7a12ab03
                  user_id: 55142883b0cc8a622d01c5a2
                  created_date: '2015-04-05T01:55:17.563Z'
                  updated_date: '2015-09-07T11:40:58.643Z'
              examples:
                response:
                  value:
                  - geofilter_id: 552168f5f8d75fe77c520e7f
                    store_ids:
                    - 551d6add1077d5fb7a12ab01
                    user_id: 55142883b0cc8a622d01c5a1
                    created_date: '2015-04-05T01:55:17.563Z'
                    updated_date: '2015-09-07T11:30:58.643Z'
                  - geofilter_id: 552168f5f8d75fe77c520e80
                    store_ids:
                    - 551d6add1077d5fb7a12ab03
                    user_id: 55142883b0cc8a622d01c5a2
                    created_date: '2015-04-05T01:55:17.563Z'
                    updated_date: '2015-09-07T11:40:58.643Z'
      summary: Create
      operationId: Create
      description: 'You may create a new single geofilter or multiple geofilters using this action.

        When creating a single geofilter the body contains a json object, when creating multiple geofilters the body contains an array of objects.

        **Warning: a maximum of 1000 items can be sent in a single request.**'
      tags:
      - Geofilters
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                store_type_names:
                  type: array
                  items:
                    type: string
                user_id:
                  type: string
              example:
                store_type_names:
                - yoobic-ice-creams
                user_id: 5babb8a69fa6ae919f675716
      security:
      - oauth2: []
  /public/api/geofilters/export?{filter}&type={type}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Geofilters
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/geofilters/import?type={type}:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Import file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Import file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Import
      operationId: Import
      description: 'See the Import file section for more information.


        ### Fields


        | Field | Format | Required | Description |

        |--------------------------|---------|:--------:|-----------------|

        |`geofilter_id` | string | | Unique geofilter id |

        |`user_id` | string | x | Unique user id |

        |`store_ids` | array | x | Unique store ids|

        |`store_client_ids` | array | | External unique ids of the stores as it may exists in your Information System|

        |`store_type_names` | array | | The names of the store types|

        |`store_type_ids` | array | | The ids of the store types|


        One of either fields is required in order to resolve the mapping between a user and store/s:


        - store_ids


        - store_client_ids


        - store_type_ids


        - store_type_names'
      tags:
      - Geofilters
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: Content-Disposition
        in: header
        description: e.g. form-data; name="file"; filename="file.csv"
        required: false
        example: form-data; name="file"; filename="file.csv"
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ImportBody'
components:
  requestBodies:
    ImportBody:
      content:
        multipart/form-data, boundary=AaB03x:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
