openapi: 3.2.0
info:
  title: YOOBIC Public Competencies API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Competencies
  description: A competency of a course allows measuring the success rate of a learner on all courses linked to that competency.
paths:
  /public/api/competencies/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  competency_id:
                    type: string
                  creator_id:
                    type: string
                  title:
                    type: string
                  tenant:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  competency_id: 61bb34a35f12370025d998da
                  creator_id: 5e1356f0c5f0e0003d305072
                  title: 'new test competency '
                  tenant: testproductv6_boost
                  created_date: '2021-12-16T12:44:19.018Z'
                  updated_date: '2021-12-16T12:44:19.018Z'
              examples:
                response:
                  value:
                    competency_id: 61bb34a35f12370025d998da
                    creator_id: 5e1356f0c5f0e0003d305072
                    title: 'new test competency '
                    tenant: testproductv6_boost
                    created_date: '2021-12-16T12:44:19.018Z'
                    updated_date: '2021-12-16T12:44:19.018Z'
      summary: Get
      operationId: Get
      description: Get a competency for the given id.
      tags:
      - Competencies
      parameters:
      - name: id
        in: path
        description: The id of the competency
        required: true
        example: 5c6e7bd9d6313e003a5b73e1
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/competencies?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        competency_id:
                          type: string
                        creator_id:
                          type: string
                        title:
                          type: string
                        tenant:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - competency_id
                      - creator_id
                      - title
                      - tenant
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - competency_id: 61bb34a35f12370025d998da
                    creator_id: 5e1356f0c5f0e0003d305072
                    title: 'new test competency '
                    tenant: testproductv6_boost
                    created_date: '2021-12-16T12:44:19.018Z'
                    updated_date: '2021-12-16T12:44:19.018Z'
                  - competency_id: 61b8de7f18a1d2002905c610
                    creator_id: 61af7b01ee30bd0025145674
                    title: 'this is a new competency '
                    tenant: new_security_tenant
                    created_date: '2021-12-14T18:12:15.385Z'
                    updated_date: '2021-12-14T18:12:15.385Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - competency_id: 61bb34a35f12370025d998da
                      creator_id: 5e1356f0c5f0e0003d305072
                      title: 'new test competency '
                      tenant: testproductv6_boost
                      created_date: '2021-12-16T12:44:19.018Z'
                      updated_date: '2021-12-16T12:44:19.018Z'
                    - competency_id: 61b8de7f18a1d2002905c610
                      creator_id: 61af7b01ee30bd0025145674
                      title: 'this is a new competency '
                      tenant: new_security_tenant
                      created_date: '2021-12-14T18:12:15.385Z'
                      updated_date: '2021-12-14T18:12:15.385Z'
      summary: Get All
      operationId: Get All
      description: Get all the competencies.
      tags:
      - Competencies
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/competencies/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Competencies
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/competencies/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Competencies
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
