openapi: 3.2.0
info:
  title: YOOBIC Public Bots API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Bots
  description: This API is exclusively used to handle bots external to YOOBIC.
paths:
  /public/api/bots/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  bot_id:
                    type: string
                  name:
                    type: string
                  is_active:
                    type: boolean
                  webhook_url:
                    type: string
                  tenant:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  bot_id: 666abc9a8c591700299636bd
                  name: FAQ Bot
                  is_active: true
                  webhook_url: https://8b3e-212-116-179-154.ngrok-free.app/webhook
                  tenant: workplace2
                  created_date: '2024-06-13T09:32:10.859Z'
                  updated_date: '2024-06-13T09:32:10.859Z'
              examples:
                response:
                  value:
                    bot_id: 666abc9a8c591700299636bd
                    name: FAQ Bot
                    is_active: true
                    webhook_url: https://8b3e-212-116-179-154.ngrok-free.app/webhook
                    tenant: workplace2
                    created_date: '2024-06-13T09:32:10.859Z'
                    updated_date: '2024-06-13T09:32:10.859Z'
      summary: Get
      operationId: Get
      description: Get a bot for the given id.
      tags:
      - Bots
      parameters:
      - name: id
        in: path
        description: The id of the bot
        required: true
        example: 666abc9a8c591700299636bd
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/bots?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        bot_id:
                          type: string
                        name:
                          type: string
                        is_active:
                          type: boolean
                        webhook_url:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - bot_id
                      - name
                      - is_active
                      - webhook_url
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - bot_id: 666abc9a8c591700299636bd
                    name: FAQ Bot
                    is_active: true
                    webhook_url: https://8b3e-212-116-179-154.ngrok-free.app/webhook
                    created_date: '2024-06-13T09:32:10.859Z'
                    updated_date: '2024-06-13T09:32:10.859Z'
                  - bot_id: 666abc9a8c591700299636be
                    name: 'FAQ Bot #2'
                    is_active: true
                    webhook_url: https://8b3e-213-117-178-155.ngrok-free.app/webhook
                    created_date: '2024-06-13T09:32:10.859Z'
                    updated_date: '2024-06-13T09:32:10.859Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - bot_id: 666abc9a8c591700299636bd
                      name: FAQ Bot
                      is_active: true
                      webhook_url: https://8b3e-212-116-179-154.ngrok-free.app/webhook
                      created_date: '2024-06-13T09:32:10.859Z'
                      updated_date: '2024-06-13T09:32:10.859Z'
                    - bot_id: 666abc9a8c591700299636be
                      name: 'FAQ Bot #2'
                      is_active: true
                      webhook_url: https://8b3e-213-117-178-155.ngrok-free.app/webhook
                      created_date: '2024-06-13T09:32:10.859Z'
                      updated_date: '2024-06-13T09:32:10.859Z'
      summary: Get All
      operationId: Get All
      description: Get all the bots.
      tags:
      - Bots
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/bots/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Bots
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/bots/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Bots
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
