openapi: 3.2.0
info:
  title: YOOBIC Public Courses API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Courses
  description: When a plan is assigned to a user it creates a course.
paths:
  /public/api/courses/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  course_id:
                    type: string
                  user_id:
                    type: string
                  plan_id:
                    type: string
                  assignment_date:
                    type: string
                  earned_points:
                    type: number
                  start_date:
                    type: string
                  finished_date:
                    type: string
                  duration:
                    type: number
                  due_date:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  course_id: 5c6e7bd9d6313e003a5b73e1
                  user_id: 5c46fccd73b0240042c8d1cd
                  plan_id: 5c5b09bb924daa006bafb347
                  assignment_date: '2019-02-21T10:22:17.130Z'
                  earned_points: 0
                  start_date: '2019-02-22T09:00:00.000Z'
                  finished_date: '2019-02-22T10:00:00.000Z'
                  duration: 60
                  due_date: '2019-03-01T08:00:00.000Z'
                  created_date: '2019-02-21T10:22:17.136Z'
                  updated_date: '2019-02-21T10:22:17.136Z'
              examples:
                response:
                  value:
                    course_id: 5c6e7bd9d6313e003a5b73e1
                    user_id: 5c46fccd73b0240042c8d1cd
                    plan_id: 5c5b09bb924daa006bafb347
                    assignment_date: '2019-02-21T10:22:17.130Z'
                    earned_points: 0
                    start_date: '2019-02-22T09:00:00.000Z'
                    finished_date: '2019-02-22T10:00:00.000Z'
                    duration: 60
                    due_date: '2019-03-01T08:00:00.000Z'
                    created_date: '2019-02-21T10:22:17.136Z'
                    updated_date: '2019-02-21T10:22:17.136Z'
      summary: Get
      operationId: Get
      description: Get a course for the given id.
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        description: The id of the course
        required: true
        example: 5c6e7bd9d6313e003a5b73e1
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/courses?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        course_id:
                          type: string
                        user_id:
                          type: string
                        plan_id:
                          type: string
                        assignment_date:
                          type: string
                        earned_points:
                          type: number
                        start_date:
                          type: string
                        finished_date:
                          type: string
                        due_date:
                          type: string
                        tenant:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - course_id
                      - user_id
                      - plan_id
                      - assignment_date
                      - tenant
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - course_id: 5c6e7bd9d6313e003a5b73e1
                    user_id: 5c46fccd73b0240042c8d1cd
                    plan_id: 5c5b09bb924daa006bafb347
                    assignment_date: '2019-02-21T10:22:17.130Z'
                    earned_points: 0
                    start_date: '2019-02-22T09:08:54.000Z'
                    finished_date: '2019-02-22T09:08:54.000Z'
                    due_date: '2019-03-01T08:00:00.000Z'
                    tenant: boost_cs
                    created_date: '2019-02-21T10:22:17.136Z'
                    updated_date: '2019-02-21T10:22:17.136Z'
                  - course_id: 5c6e7bcdd6313e003a5b73cc
                    user_id: 5c46fccc73b0240042c8d1ca
                    plan_id: 5c5b09bb924daa006bafb347
                    assignment_date: '2019-02-21T10:22:05.160Z'
                    tenant: boost_cs
                    created_date: '2019-02-21T10:22:05.163Z'
                    updated_date: '2019-02-21T10:22:05.163Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - course_id: 5c6e7bd9d6313e003a5b73e1
                      user_id: 5c46fccd73b0240042c8d1cd
                      plan_id: 5c5b09bb924daa006bafb347
                      assignment_date: '2019-02-21T10:22:17.130Z'
                      earned_points: 0
                      start_date: '2019-02-22T09:08:54.000Z'
                      finished_date: '2019-02-22T09:08:54.000Z'
                      due_date: '2019-03-01T08:00:00.000Z'
                      tenant: boost_cs
                      created_date: '2019-02-21T10:22:17.136Z'
                      updated_date: '2019-02-21T10:22:17.136Z'
                    - course_id: 5c6e7bcdd6313e003a5b73cc
                      user_id: 5c46fccc73b0240042c8d1ca
                      plan_id: 5c5b09bb924daa006bafb347
                      assignment_date: '2019-02-21T10:22:05.160Z'
                      tenant: boost_cs
                      created_date: '2019-02-21T10:22:05.163Z'
                      updated_date: '2019-02-21T10:22:05.163Z'
      summary: Get All
      operationId: Get All
      description: Get all the courses.
      tags:
      - Courses
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/courses/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Courses
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/courses/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Courses
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
