openapi: 3.2.0
info:
  title: YOOBIC Public Roles API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Roles
  description: Get the list of Roles available for the users in your organization.
paths:
  /public/api/acl-roles/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  acl_role_id:
                    type: string
                  client_role:
                    type: string
                  client_role_extension:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  acl_role_id: 635fa9a8fffb8783206ea224
                  client_role: ROLESTORE
                  client_role_extension: test
                  created_date: '2022-10-31T10:55:36.857Z'
                  updated_date: '2022-10-31T10:55:36.857Z'
              examples:
                response:
                  value:
                    acl_role_id: 635fa9a8fffb8783206ea224
                    client_role: ROLESTORE
                    client_role_extension: test
                    created_date: '2022-10-31T10:55:36.857Z'
                    updated_date: '2022-10-31T10:55:36.857Z'
      summary: Get
      operationId: Get
      description: Get a role for the given id.
      tags:
      - Roles
      parameters:
      - name: id
        in: path
        description: The id of the role
        required: true
        example: 635fa9a8fffb8783206ea224
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/acl-roles?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    acl_role_id:
                      type: string
                    client_role:
                      type: string
                    client_role_extension:
                      type: string
                    created_date:
                      type: string
                    updated_date:
                      type: string
                  required:
                  - acl_role_id
                  - client_role
                  - created_date
                  - updated_date
                example:
                - acl_role_id: 5f591f87933fa329c5956d7d
                  client_role: ROLESTORE
                  client_role_extension: Tudor
                  created_date: '2020-09-09T18:31:35.542Z'
                  updated_date: '2022-10-31T10:54:27.973Z'
                - acl_role_id: 61538d4de9967a003670703c
                  client_role: ROLEVIEWER
                  created_date: '2021-09-28T21:46:53.325Z'
                  updated_date: '2022-10-28T21:01:37.131Z'
              examples:
                response:
                  value:
                  - acl_role_id: 5f591f87933fa329c5956d7d
                    client_role: ROLESTORE
                    client_role_extension: Tudor
                    created_date: '2020-09-09T18:31:35.542Z'
                    updated_date: '2022-10-31T10:54:27.973Z'
                  - acl_role_id: 61538d4de9967a003670703c
                    client_role: ROLEVIEWER
                    created_date: '2021-09-28T21:46:53.325Z'
                    updated_date: '2022-10-28T21:01:37.131Z'
      summary: Get All
      operationId: Get All
      description: Get all the roles.
      tags:
      - Roles
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/acl-roles/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Roles
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/acl-roles/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Roles
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
