openapi: 3.2.0
info:
  title: YOOBIC Public Plans API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Plans
  description: A plan is the main description of a course that's assigned to users.
paths:
  /public/api/plans/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  plan_id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  tenant:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  plan_id: 5c015012ad45490041a52f64
                  title: QA - Document
                  description: Course to test Documents Lessons
                  tenant: qa_boost
                  created_date: '2018-11-30T14:58:26.716Z'
                  updated_date: '2019-01-25T13:34:14.819Z'
              examples:
                response:
                  value:
                    plan_id: 5c015012ad45490041a52f64
                    title: QA - Document
                    description: Course to test Documents Lessons
                    tenant: qa_boost
                    created_date: '2018-11-30T14:58:26.716Z'
                    updated_date: '2019-01-25T13:34:14.819Z'
      summary: Get
      operationId: Get
      description: Get a plan for the given id.
      tags:
      - Plans
      parameters:
      - name: id
        in: path
        description: The id of the plan
        required: true
        example: 5c015012ad45490041a52f64
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/plans/{id}/assign:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                - 5e4514ac98ab7400553bf15f
                - 5e4514ac98ab7400553bf160
              examples:
                response:
                  value:
                  - 5e4514ac98ab7400553bf15f
                  - 5e4514ac98ab7400553bf160
      summary: Assign
      operationId: Assign
      description: Assign a plan to users. Response is an array of courses ids created for each assigned user.
      tags:
      - Plans
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/plans?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        plan_id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                        tenant:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                      required:
                      - plan_id
                      - title
                      - description
                      - tenant
                      - created_date
                      - updated_date
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - plan_id: 5c015012ad45490041a52f64
                    title: QA - Document
                    description: Course to test Documents Lessons
                    tenant: qa_boost
                    created_date: '2018-11-30T14:58:26.716Z'
                    updated_date: '2019-01-25T13:34:14.819Z'
                  - plan_id: 5c015558ad45490041a53473
                    title: QA - Video
                    description: Course to test Video Lessons
                    tenant: qa_boost
                    created_date: '2018-11-30T15:20:56.392Z'
                    updated_date: '2019-01-25T13:34:05.098Z'
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - plan_id: 5c015012ad45490041a52f64
                      title: QA - Document
                      description: Course to test Documents Lessons
                      tenant: qa_boost
                      created_date: '2018-11-30T14:58:26.716Z'
                      updated_date: '2019-01-25T13:34:14.819Z'
                    - plan_id: 5c015558ad45490041a53473
                      title: QA - Video
                      description: Course to test Video Lessons
                      tenant: qa_boost
                      created_date: '2018-11-30T15:20:56.392Z'
                      updated_date: '2019-01-25T13:34:05.098Z'
      summary: Get All
      operationId: Get All
      description: Get all the plans.
      tags:
      - Plans
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/plans/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Plans
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/plans/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Plans
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
