openapi: 3.2.0
info:
  title: YOOBIC Public Lessons API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Lessons
  description: Lessons are the activities the users perform during their trainings.
paths:
  /public/api/lessons/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      total:
                        type: number
                      skip:
                        type: number
                      limit:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        lesson_id:
                          type: string
                        title:
                          type: string
                        type:
                          type: string
                        campaign_id:
                          type: string
                        plan_id:
                          type: string
                        course_id:
                          type: string
                        user_id:
                          type: string
                        status:
                          type: string
                        score:
                          type: object
                          properties:
                            total:
                              type: number
                            value:
                              type: number
                        duration:
                          type: number
                        validated:
                          type: boolean
                        tenant:
                          type: string
                        created_date:
                          type: string
                        updated_date:
                          type: string
                        answers:
                          type: array
                          items:
                            type: object
                            properties:
                              question_id:
                                type: string
                              question_type:
                                type: string
                              question:
                                type: string
                              page_number:
                                type: number
                              question_number:
                                type: number
                              answer:
                                type: number
                example:
                  paging:
                    total: 2
                    skip: 0
                    limit: 1000
                  data:
                  - lesson_id: 5c7004c1b31ec3003a56af4e
                    title: Feedback
                    type: lesson
                    campaign_id: 5c582b8f4a35650044aea049
                    plan_id: 5bf2d58ae553190041467eef
                    course_id: 5bf4448528b7420041ba9b62
                    user_id: 5beee3717fc4d50043801a97
                    status: finished
                    score:
                      total: 0
                      value: 0
                    duration: 2.3
                    validated: true
                    tenant: testproductv6_boost
                    created_date: '2019-02-22T14:18:41.667Z'
                    updated_date: '2019-02-22T14:18:41.667Z'
                    answers:
                    - question_id: e886902d-ddef-43c1-8894-c9f5f101fa56
                      question_type: feedback
                      question: Feedback
                      page_number: 1
                      question_number: 1
                      answer: 3
              examples:
                response:
                  value:
                    paging:
                      total: 2
                      skip: 0
                      limit: 1000
                    data:
                    - lesson_id: 5c7004c1b31ec3003a56af4e
                      title: Feedback
                      type: lesson
                      campaign_id: 5c582b8f4a35650044aea049
                      plan_id: 5bf2d58ae553190041467eef
                      course_id: 5bf4448528b7420041ba9b62
                      user_id: 5beee3717fc4d50043801a97
                      status: finished
                      score:
                        total: 0
                        value: 0
                      duration: 2.3
                      validated: true
                      tenant: testproductv6_boost
                      created_date: '2019-02-22T14:18:41.667Z'
                      updated_date: '2019-02-22T14:18:41.667Z'
                      answers:
                      - question_id: e886902d-ddef-43c1-8894-c9f5f101fa56
                        question_type: feedback
                        question: Feedback
                        page_number: 1
                        question_number: 1
                        answer: 3
      summary: Get
      operationId: Get
      description: Get a lesson for the given id.
      tags:
      - Lessons
      parameters:
      - name: id
        in: path
        description: The id of the lesson
        required: true
        example: 5c7004c1b31ec3003a56af4e
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/lessons?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    lesson_id:
                      type: string
                    title:
                      type: string
                    type:
                      type: string
                    campaign_id:
                      type: string
                    plan_id:
                      type: string
                    course_id:
                      type: string
                    user_id:
                      type: string
                    status:
                      type: string
                    score:
                      type: object
                      properties:
                        total:
                          type: number
                        value:
                          type: number
                        isPercentage:
                          type: boolean
                        completed:
                          type: number
                    validated:
                      type: boolean
                    tenant:
                      type: string
                    created_date:
                      type: string
                    updated_date:
                      type: string
                    answers:
                      type: array
                      items:
                        type: object
                        properties:
                          question_id:
                            type: string
                          question_type:
                            type: string
                          question:
                            type: string
                          page_number:
                            type: number
                          question_number:
                            type: number
                          answer:
                            type: array
                            items:
                              type: array
                              items: {}
                        required:
                        - question_id
                        - question_type
                        - question
                        - page_number
                        - question_number
                        - answer
                    points:
                      type: number
                  required:
                  - lesson_id
                  - title
                  - type
                  - campaign_id
                  - plan_id
                  - course_id
                  - user_id
                  - status
                  - score
                  - validated
                  - tenant
                  - created_date
                  - updated_date
                  - answers
                example:
                - lesson_id: 5c7004c1b31ec3003a56af4e
                  title: Feedback
                  type: lesson
                  campaign_id: 5c582b8f4a35650044aea049
                  plan_id: 5bf2d58ae553190041467eef
                  course_id: 5bf4448528b7420041ba9b62
                  user_id: 5beee3717fc4d50043801a97
                  status: finished
                  score:
                    total: 0
                    value: 0
                  validated: true
                  tenant: testproductv6_boost
                  created_date: '2019-02-22T14:18:41.667Z'
                  updated_date: '2019-02-22T14:18:41.667Z'
                  answers:
                  - question_id: e886902d-ddef-43c1-8894-c9f5f101fa56
                    question_type: feedback
                    question: Feedback
                    page_number: 1
                    question_number: 1
                    answer: 3
                - lesson_id: 5c7004b8b31ec3003a56af0c
                  title: Categories
                  type: lesson
                  campaign_id: 5c582b5b4a35650044aea033
                  plan_id: 5bf2d58ae553190041467eef
                  course_id: 5bf4448528b7420041ba9b62
                  user_id: 5beee3717fc4d50043801a97
                  status: finished
                  points: 10
                  score:
                    total: 1
                    value: 100
                    isPercentage: true
                    completed: 1
                  validated: true
                  tenant: testproductv6_boost
                  created_date: '2019-02-22T14:18:32.878Z'
                  updated_date: '2019-02-22T14:18:32.878Z'
                  answers:
                  - question_id: fd91d037-769d-46d8-ac56-059a85db745e
                    question_type: categorizewords
                    question: Categorize words
                    page_number: 1
                    question_number: 1
                    answer:
                    - - '1'
                      - '2'
                      - '3'
                    - - A
                      - B
                      - C
              examples:
                response:
                  value:
                  - lesson_id: 5c7004c1b31ec3003a56af4e
                    title: Feedback
                    type: lesson
                    campaign_id: 5c582b8f4a35650044aea049
                    plan_id: 5bf2d58ae553190041467eef
                    course_id: 5bf4448528b7420041ba9b62
                    user_id: 5beee3717fc4d50043801a97
                    status: finished
                    score:
                      total: 0
                      value: 0
                    validated: true
                    tenant: testproductv6_boost
                    created_date: '2019-02-22T14:18:41.667Z'
                    updated_date: '2019-02-22T14:18:41.667Z'
                    answers:
                    - question_id: e886902d-ddef-43c1-8894-c9f5f101fa56
                      question_type: feedback
                      question: Feedback
                      page_number: 1
                      question_number: 1
                      answer: 3
                  - lesson_id: 5c7004b8b31ec3003a56af0c
                    title: Categories
                    type: lesson
                    campaign_id: 5c582b5b4a35650044aea033
                    plan_id: 5bf2d58ae553190041467eef
                    course_id: 5bf4448528b7420041ba9b62
                    user_id: 5beee3717fc4d50043801a97
                    status: finished
                    points: 10
                    score:
                      total: 1
                      value: 100
                      isPercentage: true
                      completed: 1
                    validated: true
                    tenant: testproductv6_boost
                    created_date: '2019-02-22T14:18:32.878Z'
                    updated_date: '2019-02-22T14:18:32.878Z'
                    answers:
                    - question_id: fd91d037-769d-46d8-ac56-059a85db745e
                      question_type: categorizewords
                      question: Categorize words
                      page_number: 1
                      question_number: 1
                      answer:
                      - - '1'
                        - '2'
                        - '3'
                      - - A
                        - B
                        - C
      summary: Get All
      operationId: Get All
      description: Get all the lessons.
      tags:
      - Lessons
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/lessons/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Lessons
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/lessons/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Lessons
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
