openapi: 3.2.0
info:
  title: YOOBIC Public Community Posts API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Community Posts
  description: The posts made in the communities appear both in the community newsfeed and in the main newsfeed, along with the posts in the normal newsfeed (unless otherwise configured in the Community).
paths:
  /public/api/community-posts/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: string
                  description:
                    type: string
                  community_id:
                    type: string
                  user_id:
                    type: string
                  publish_type:
                    type: string
                  publish_date:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  post_id: 677d40dc0241bb002127310f
                  description: <div>Working test</div>
                  community_id: 667ac0b15ba1350028ac0b99
                  user_id: 66150878202c1cfafdb4f8f5
                  publish_type: postnow
                  publish_date: '2025-01-07T14:57:32.036Z'
                  created_date: '2025-01-07T14:57:32.122Z'
                  updated_date: '2025-01-07T14:57:32.122Z'
              examples:
                response:
                  value:
                    post_id: 677d40dc0241bb002127310f
                    description: <div>Working test</div>
                    community_id: 667ac0b15ba1350028ac0b99
                    user_id: 66150878202c1cfafdb4f8f5
                    publish_type: postnow
                    publish_date: '2025-01-07T14:57:32.036Z'
                    created_date: '2025-01-07T14:57:32.122Z'
                    updated_date: '2025-01-07T14:57:32.122Z'
      summary: Get
      operationId: Get
      description: Get a post for a given id
      tags:
      - Community Posts
      parameters:
      - name: id
        in: path
        description: The id of the post
        required: true
        example: 677d40dc0241bb002127310f
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/community-posts/?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Get all posts
      operationId: Get all posts
      description: Get all posts.
      tags:
      - Community Posts
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{"where":{"community_id": "667ac0b15ba1350028ac0b99"}}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/community-posts/{community_post_id}/comments?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Get all post comments
      operationId: Get all post comments
      description: Get all post comments.
      tags:
      - Community Posts
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{"where”:{"comment": "I want to join"}}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/community-posts:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: string
                  description:
                    type: string
                  community_id:
                    type: string
                  user_id:
                    type: string
                  publish_type:
                    type: string
                  publish_date:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  post_id: 677e3e49b855a6001ff46388
                  description: <div>Welcome everyone!</div>
                  community_id: 667ac0b15ba1350028ac0b99
                  user_id: 6628ed6adc1960a7aa5c7ce4
                  publish_type: postnow
                  publish_date: '2025-01-08T07:57:32.036Z'
                  created_date: '2025-01-08T08:58:49.102Z'
                  updated_date: '2025-01-08T08:58:49.102Z'
              examples:
                response:
                  value:
                    post_id: 677e3e49b855a6001ff46388
                    description: <div>Welcome everyone!</div>
                    community_id: 667ac0b15ba1350028ac0b99
                    user_id: 6628ed6adc1960a7aa5c7ce4
                    publish_type: postnow
                    publish_date: '2025-01-08T07:57:32.036Z'
                    created_date: '2025-01-08T08:58:49.102Z'
                    updated_date: '2025-01-08T08:58:49.102Z'
      summary: Create a post
      operationId: Create a post
      tags:
      - Community Posts
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                community_id:
                  type: string
                user_id:
                  type: string
                publish_type:
                  type: string
                publish_date:
                  type: string
              example:
                description: <div>Welcome everyone!</div>
                community_id: 667ac0b15ba1350028ac0b99
                user_id: 6628ed6adc1960a7aa5c7ce4
                publish_type: postnow
                publish_date: '2025-01-08T07:57:32.036Z'
      security:
      - oauth2: []
  /public/api/community-posts/{community_post_id}/comments:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: string
                  user_id:
                    type: string
                  date:
                    type: string
                  comment:
                    type: string
                  community_id:
                    type: string
                  community_post_id:
                    type: string
                  created_date:
                    type: string
                  updated_date:
                    type: string
                example:
                  comment_id: 677e3f43b855a6001ff464a7
                  user_id: 6628ed6adc1960a7aa5c7ce4
                  date: '2025-01-08T09:02:59.707Z'
                  comment: Good to know :)
                  community_id: 667ac0b15ba1350028ac0b99
                  community_post_id: 677ba82156e14b001e8cab37
                  created_date: '2025-01-08T09:02:59.728Z'
                  updated_date: '2025-01-08T09:02:59.728Z'
              examples:
                response:
                  value:
                    comment_id: 677e3f43b855a6001ff464a7
                    user_id: 6628ed6adc1960a7aa5c7ce4
                    date: '2025-01-08T09:02:59.707Z'
                    comment: Good to know :)
                    community_id: 667ac0b15ba1350028ac0b99
                    community_post_id: 677ba82156e14b001e8cab37
                    created_date: '2025-01-08T09:02:59.728Z'
                    updated_date: '2025-01-08T09:02:59.728Z'
      summary: Create a post comment
      operationId: Create a post comment
      tags:
      - Community Posts
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                comment:
                  type: string
              example:
                user_id: 6628ed6adc1960a7aa5c7ce4
                comment: Good to know :)
      security:
      - oauth2: []
  /public/api/community-posts/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Community Posts
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/community-posts/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Community Posts
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
components:
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  requestBodies:
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
