openapi: 3.2.0
info:
  title: YOOBIC Public Events API
  version: ''
  description: Welcome to the **YOOBIC Public API** documentation.
servers:
- url: https://<base_url>/
tags:
- name: Events
  description: Events can be created and managed through the YOOBIC app and are displayed in the calendar.
paths:
  /public/api/events/{id}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
      summary: Get
      operationId: Get
      description: Get a event for the given id.
      tags:
      - Events
      parameters:
      - name: id
        in: path
        description: The id of the event
        required: true
        example: 61b9b435c8f864003a552378
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      security:
      - oauth2: []
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  event_id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  start_date:
                    type: string
                  end_date:
                    type: string
                  event_type:
                    type: string
                  images:
                    type: array
                    items: {}
                  created_date:
                    type: string
                  updated_date:
                    type: string
                  user_ids:
                    type: array
                    items:
                      type: string
                  tags:
                    type: array
                    items:
                      type: string
                  timezone:
                    type: string
                example:
                  event_id: 62876c7ad1d606003e43d8bc
                  title: private event
                  description: update description
                  start_date: '2022-05-23T10:24:00.000Z'
                  end_date: '2022-05-23T15:25:00.000Z'
                  event_type: private
                  images: []
                  created_date: '2022-05-20T10:24:58.655Z'
                  updated_date: '2022-05-20T10:24:58.655Z'
                  user_ids:
                  - 5f23dc9e342004004927778e
                  - 5f3cfa761e8fdf003bf1faba
                  - 628361451008ce002508afe1
                  - 628364ac1008ce00250a18c2
                  tags:
                  - event_tag
                  timezone: America/New_York
              examples:
                response:
                  value:
                    event_id: 62876c7ad1d606003e43d8bc
                    title: private event
                    description: update description
                    start_date: '2022-05-23T10:24:00.000Z'
                    end_date: '2022-05-23T15:25:00.000Z'
                    event_type: private
                    images: []
                    created_date: '2022-05-20T10:24:58.655Z'
                    updated_date: '2022-05-20T10:24:58.655Z'
                    user_ids:
                    - 5f23dc9e342004004927778e
                    - 5f3cfa761e8fdf003bf1faba
                    - 628361451008ce002508afe1
                    - 628364ac1008ce00250a18c2
                    tags:
                    - event_tag
                    timezone: America/New_York
      summary: Partial Update
      operationId: Partial Update
      description: Update a subset of properties of an event
      tags:
      - Events
      parameters:
      - name: id
        in: path
        description: The id of the event
        required: true
        example: 61b9b435c8f864003a552378
        schema:
          type: string
      - name: id
        in: path
        description: The id of the event
        required: true
        example: 62876c7ad1d606003e43d8bc
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tags:
                  type: array
                  items:
                    type: string
                description:
                  type: string
                timezone:
                  type: string
              example:
                tags:
                - event_tag
                description: update description
                timezone: America/New_York
      security:
      - oauth2: []
    delete:
      responses:
        '204':
          description: No Content
          headers: {}
      summary: Delete
      operationId: Delete
      description: Delete an event by id.
      tags:
      - Events
      parameters:
      - name: id
        in: path
        description: The id of the event
        required: true
        example: 61b9b435c8f864003a552378
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/events/{id}/invitees:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Invitees
      operationId: Invitees
      description: 'Export list of invitees of an event.


        | Field | Format | Description |

        |-------------|--------|-------------------------------------------|

        | user_id | string | id of the user |

        | username | string | username of the user |

        | email | string | email of the user |

        | first_name | string | first name of the user |

        | last_name | string | last name of the user |

        | attendance | string | attendance status of the user:

        • `null` if no answer from user

        • `join`

        • `maybe`

        • `decline` |'
      tags:
      - Events
      parameters:
      - name: id
        in: path
        description: The id of the event
        required: true
        example: 62876c7ad1d606003e43d8bc
        schema:
          type: string
      security:
      - oauth2: []
  /public/api/events?filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      skip:
                        type: number
                      limit:
                        type: number
                      total:
                        type: number
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        event_id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                        start_date:
                          type: string
                        end_date:
                          type: string
                        event_type:
                          type: string
                        images:
                          type: array
                          items: {}
                        created_date:
                          type: string
                        updated_date:
                          type: string
                        group_ids:
                          type: array
                          items:
                            type: string
                        shared:
                          type: boolean
                      required:
                      - event_id
                      - title
                      - description
                      - start_date
                      - end_date
                      - event_type
                      - images
                      - shared
                      - created_date
                      - updated_date
                      - group_ids
                example:
                  paging:
                    skip: 0
                    limit: 2
                    total: 5
                  data:
                  - event_id: 62a0c411fcbce30026aee2c8
                    title: Share to newsfeed event
                    description: shared in feed
                    start_date: '2022-06-08T15:45:14.688Z'
                    end_date: '2022-06-08T16:45:18.434Z'
                    event_type: public
                    images: []
                    created_date: '2022-06-08T15:45:21.045Z'
                    updated_date: '2022-06-08T16:20:56.579Z'
                    group_ids:
                    - documetation_api
                    shared: true
                  - event_id: 62a0c83271670d71266b9a55
                    title: Don't share to newsfeed
                    description: <div>Is it working?</div>
                    start_date: '2022-06-08T15:45:14.688Z'
                    end_date: '2022-06-08T16:45:18.434Z'
                    event_type: public
                    images: []
                    shared: false
                    created_date: '2022-06-08T16:02:58.878Z'
                    updated_date: '2022-06-08T16:20:56.028Z'
                    group_ids:
                    - documetation_api
              examples:
                response:
                  value:
                    paging:
                      skip: 0
                      limit: 2
                      total: 5
                    data:
                    - event_id: 62a0c411fcbce30026aee2c8
                      title: Share to newsfeed event
                      description: shared in feed
                      start_date: '2022-06-08T15:45:14.688Z'
                      end_date: '2022-06-08T16:45:18.434Z'
                      event_type: public
                      images: []
                      created_date: '2022-06-08T15:45:21.045Z'
                      updated_date: '2022-06-08T16:20:56.579Z'
                      group_ids:
                      - documetation_api
                      shared: true
                    - event_id: 62a0c83271670d71266b9a55
                      title: Don't share to newsfeed
                      description: <div>Is it working?</div>
                      start_date: '2022-06-08T15:45:14.688Z'
                      end_date: '2022-06-08T16:45:18.434Z'
                      event_type: public
                      images: []
                      shared: false
                      created_date: '2022-06-08T16:02:58.878Z'
                      updated_date: '2022-06-08T16:20:56.028Z'
                      group_ids:
                      - documetation_api
      summary: Get All
      operationId: Get All
      description: Get all the events.
      tags:
      - Events
      parameters:
      - name: filter
        in: query
        description: A valid JSON filter object
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/events:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            '*/*':
              schema:
                type: object
                properties:
                  event_id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  start_date:
                    type: string
                  end_date:
                    type: string
                  event_type:
                    type: string
                  group_ids:
                    type: array
                    items:
                      type: string
                  images:
                    type: array
                    items:
                      type: string
                  event_category:
                    type: string
                  store_id:
                    type: string
                example:
                  event_id: 5f3e4be0c920a5003b57bbed
                  title: EVENT 1
                  description: <div>This is my new description 1</div>
                  start_date: '2022-05-29T08:00:00.000Z'
                  end_date: '2022-05-29T13:00:00.000Z'
                  event_type: public
                  group_ids:
                  - documentation_admin
                  - documentation_stores
                  images:
                  - test.jpg
                  event_category: EVENTCATEGORY1
                  store_id: 5f3e4be0c920a5003b57bbec
      summary: Create
      operationId: Create
      description: 'You may create a new single or multiple events using this action.

        When creating a single event object the body contains a json object, when creating multiple events objects the body contains an array of objects.

        **Warning: a maximum of 1000 items can be sent in a single request.**'
      tags:
      - Events
      parameters:
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                start_date:
                  type: string
                end_date:
                  type: string
                event_type:
                  type: string
                group_ids:
                  type: array
                  items:
                    type: string
                images:
                  type: array
                  items:
                    type: string
                event_category:
                  type: string
                store_id:
                  type: string
              example:
                title: EVENT 1
                description: <div>This is my new description 1</div>
                start_date: '2022-05-29T08:00:00.000Z'
                end_date: '2022-05-29T13:00:00.000Z'
                event_type: public
                group_ids:
                - documentation_admin
                - documentation_stores
                images:
                - test.jpg
                event_category: EVENTCATEGORY1
                store_id: 5f3e4be0c920a5003b57bbec
      security:
      - oauth2: []
  /public/api/events/count?where={where}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                example:
                  count: 10
              examples:
                response:
                  value:
                    count: 10
      summary: Count
      operationId: Count
      description: Count all the existing entities based on the where filter
      tags:
      - Events
      parameters:
      - name: where
        in: query
        description: A valid JSON [Where filter](#section-api-requests-filter-where)
        required: false
        example: '{ "property": "value" }'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/events/export?type={type}&filter={filter}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Export file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Export file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Export
      operationId: Export
      description: 'Export all results as a file.

        This action is asynchronous and returns the id of a job. See `jobs` endpoint to query the status of the job. The file will contain the results with all of the fields specified on the resource.'
      tags:
      - Events
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: filter
        in: query
        description: A valid JSON filter object (does not accept a `fields` filter)
        required: false
        example: '{}'
        schema:
          type: string
      - name: Accept
        in: header
        description: e.g. application/json
        required: false
        example: application/json
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/Get_AllBody'
  /public/api/events/import?type={type}:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                  priority:
                    type: number
                  nextRunAt:
                    type: string
                  _id:
                    type: string
                example:
                  name: Import file
                  type: normal
                  priority: 0
                  nextRunAt: '2018-09-11T15:56:05.387Z'
                  _id: 5b97e5954b99568b4b9101af
              examples:
                response:
                  value:
                    name: Import file
                    type: normal
                    priority: 0
                    nextRunAt: '2018-09-11T15:56:05.387Z'
                    _id: 5b97e5954b99568b4b9101af
      summary: Import
      operationId: Import
      description: '### Fields


        | Field | Format | Required | Description |

        |----------------------|:--------------:|:--------:|:--------------------------|

        |`event_id` | string | | Unique id of the event |

        |`title` | string | x | The title of the event |

        |`description` | string | x | The description of the event. HTML can be used for formatting|

        |`start_date` | date | x | Start date of the event in UTC|

        |`end_date` | date | x | End date of the event in UTC|

        |`event_type` | string | x | `private` or `public` |

        |`all_day` | boolean | | `true` or `false`. if `true`, start_date should equal to end_date|

        |`tags` | array | | Event’s list of tags |

        |`event_category` | string | | Category of the event. Categories need to be defined in the database in the `translations` collection|

        |`user_ids` | array | | Required for private events only. Ignored for public events. User ids that are invited to this event|

        |`group_ids` | array | | | Required for public events. Ignored for private events. Group ids of users who should be invited to this event|

        |`images` | array | | | Links to uploaded images. Used as illustration on the event page. Max 3 images per event|

        |`store_id` | string | | Store the event is linked to|

        |`shared` | boolean | | If event shared on feeds (true/false)|

        |`created_date` | date | | Creation date |

        |`updated_date` | date | | Last update date |'
      tags:
      - Events
      parameters:
      - name: type
        in: path
        description: The type of file, either `csv` (default value) or `excel`
        required: true
        example: csv
        schema:
          type: string
      - name: Content-Disposition
        in: header
        description: e.g. form-data; name="file"; filename="file.csv"
        required: false
        example: form-data; name="file"; filename="file.csv"
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ImportBody'
components:
  requestBodies:
    ImportBody:
      content:
        multipart/form-data, boundary=AaB03x:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
    Get_AllBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              Authorization:
                $ref: '#/components/schemas/Default_Header'
  schemas:
    Default_Header:
      type: object
      required:
      - Authorization
      properties:
        Authorization:
          type: string
          example: Bearer JWT
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: /
          scopes: {}
